- hosts: localhost
  tasks:
  - name: Create a k8s namespace
    k8s:
      name: projectsa
      api_version: v1
      kind: Namespace
      state: present
  - name: Create first deploy
    k8s:
      namespace: projectsa
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: webserver
          labels:
            app: apache
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: apache
          template:
            metadata:
              labels:
                app: apache
            spec:
              containers:
              - name: php-apache
                image: {{ image_id }}
                ports:
                - containerPort: 80
